name: Go Format Check

on: [push, pull_request]

jobs:
  gofmt:
    name: Check Go Formatting
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21.0'  

    - name: Check formatting
      run: |
        unformatted=$(gofmt -l .)
        if [ -n "$unformatted" ]; then
          echo "These files are not formatted properly:"
          echo "$unformatted"
          exit 1
        fi
